# ~/.tmuxinator/bamoe8-run.yml
# you can make as many tabs as you wish...

name: bamoe8-run
root: ~/Install/bamoe8
socket_name: foo # Remove to use default socket
# pre_window: rbenv shell 2.0.0-p247 # Runs in each tab and pane
tmux_detached: false
windows:
  # - editor:
  #     pre:
  #       - echo "I get run in each pane, before each pane command!"
  #       -
  #     layout: main-vertical
  #     panes:
  #       - echo "vim"
  #       - #empty, will just run plain bash
  #       - pane_with_multiple_commands:
  #           - echo "server"
  #           - echo "Hello"
  # - guard:
  #     layout: tiled
  #     pre:
  #       - echo "I get run in each pane."
  #       - echo "Before each pane command!"
  #     panes:
  #       -
  #       - #empty, will just run plain bash
  #       -
  - run: 